### ISSUE TITLE
🛑 Blog is down

### ISSUE THREAD

**Issue by lfreneda** [FieldControl/status#1]
In [`d9c7d70`](https://github.com/FieldControl/status/commit/d9c7d7005abea0aa5d0445063c4aaea991873da9
), Blog (ONERING_URL) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by brunoperissotti-field** [comment]
Teste do comentário

**Comment by lfreneda** [comment]
QQQQQ
